name: faceblur
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  camera: ^0.10.5+7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mlkit_face_detection: ^0.9.0
  image: ^4.1.3
  image_picker: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
